# =============================================================================
# EXTERNAL TOOLS (Manual Installation Required):
#
# NOTE: These system-level tools are not managed by conda/pip and must be
#       installed manually before running the project setup scripts.
#
# - Allure CLI is required for report serving:
#     scoop install allure      # (Recommended on Windows)
#     choco install allure      # (Alternative on Windows)
#     brew install allure       # (macOS)
#     sudo apt install allure   # (Linux, if available)
#     # NOTE: Do NOT add 'allure-cmd' to requirements.txt or environment.yaml.
#     #       The Allure CLI is NOT a Python/pip package.
#
# - Java (required for Allure CLI):
#     scoop bucket add java     # (Required before installing openjdk with Scoop)
#     scoop install openjdk     # (Recommended on Windows)
#     choco install openjdk     # (Alternative on Windows)
#
# - eza (for tree view):
#     scoop install eza         # (Windows)
#     brew install eza          # (macOS)
#     sudo apt install eza      # (Linux, if available)
#
# - Node.js Version Management (REQUIRED for frontend tooling):
#     nvm (Node Version Manager) is the preferred method for installing and managing Node.js versions.
#     - nvm for Windows: https://github.com/coreybutler/nvm-windows
#     - nvm for macOS/Linux: https://github.com/nvm-sh/nvm
#     # NOTE: Do NOT use conda to manage Node.js for this project.
#     #       Always use nvm for installing and switching Node.js versions.
#
# - Node.js (required for Sass CLI and other frontend tooling):
#     # After installing nvm, install Node.js using nvm:
#     nvm install lts
#     nvm use lts
#     node --version
#     npm --version
#
# - Sass CLI (for SCSS compilation):
#     npm install -g sass
#     # To check if Sass CLI is installed:
#     #     sass --version
#     # If you see "'sass' is not recognized" or "command not found", install it with:
#     #     npm install -g sass
#     # Usage:
#     #   Compile a single SCSS file to CSS:
#     #     sass path/to/input.scss path/to/output.css
#     #   Example:
#     #     sass src/presentation/api_server/flask_app/static/css/main.scss src/presentation/api_server/flask_app/static/css/main.css
#     #   Watch a folder for changes (recommended for development):
#     #     sass --watch src/presentation/api_server/flask_app/static/css:src/presentation/api_server/flask_app/static/css
#     # NOTE: Do NOT add 'sass' to requirements.txt or environment.yaml.
#     #       The Sass CLI is NOT a Python/pip package.
#
# - Angular CLI (for Angular development):
#     npm install -g @angular/cli
#     # To check if Angular CLI is installed:
#     #     ng --version
#     # This is required for scaffolding and serving the Angular presentation layer.
#
# - Python Sass (for programmatic SCSS compilation, NOT for command-line use):
#     conda install -c conda-forge sass
#     # NOTE: This package is NOT available for Windows via conda-forge.
#     # It is only available for Linux and macOS.
#     # This installs the 'python-sass' package, which allows you to compile SCSS from within Python code.
#     # It does NOT provide the 'sass' command-line tool for frontend workflows.
#     # Only use this if you need to compile SCSS in Python scripts or Flask extensions, and you are NOT on Windows.
#     # For most frontend development, use the Dart Sass CLI via npm (see above).
#
# - JavaScript Frontend Testing (for Angular/React/Vue, etc.):
#     # For JS frontend testing (Jasmine, Karma, Cypress, etc.), use npm in your frontend directory:
#     #   npm install --save-dev jasmine karma karma-chrome-launcher karma-jasmine karma-jasmine-html-reporter
#     #   npm install --save-dev cypress
#     # Do NOT add these to environment.yaml or requirements.txt; they are Node.js tools.
# =============================================================================
name: jennai-root
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - cudatoolkit=11.8
  - cudnn=8.9.7
  - pytorch
  - torchvision
  - torchaudio
  - torchtext
  - torchdata
  - pytorch-cuda=11.8
  - torchtext
  - torchdata
  - nodejs
  - flask
  - flask-cors
  - flask-assets
  - numpy
  - pandas
  - requests
  - matplotlib
  - jupyter
  - markdown
  - pyyaml  # Required for the dynamic conda_update.py script
  - python-dotenv
  - pre-commit
  - pip
  - conda-forge::inquirerpy>=0.3.4 # Explicitly specify channel for InquirerPy
  - pip:
      - -r requirements.txt